// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Provide a dummy URL during build if DATABASE_URL is not set.
    // This allows the build to succeed without exposing real credentials.
    url: process.env.DATABASE_URL || "postgresql://dummy:dummy@localhost:5432/dummy?schema=public",
  },
});
